export const SET_AUTH_CONTEXT = 'SET_AUTH_CONTEXT'
export const SET_SIGNIN_STATUS = 'SET_SIGNIN_STATUS'
export const SET_FILE_INFO = 'SET_FILE_INFO'
export const SET_LAYOUT_DATA = 'SET_LAYOUT_DATA'
export const SET_PALETTE_ITEM = 'SET_PALETTE_ITEM'

